name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: check homework "Git GUI"
      shell: bash
      run: scripts/homework1.sh
